version: '3.9'
services:
  postgres:
    image: 'postgres:14.3-alpine'
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres-ecm-local: